name: Hello World

on: 
    push:
        branches:
        - main
    workflow_dispatch:
#   schedule:
#     - cron: "*/1 * * * *"


jobs:
    deploy:
     strategy:
        fail-fast: false
        max-parallel: 2
        matrix:
            os: [ubuntu-latest, windows-latest]
            image: [alpine, hello-world]
            exclude:
               - os: windows-latest
                 image: alpine
            include:
               - os: ubuntu-latest
                 image: amd64/alpine
     runs-on: ${{ matrix.os }} 
     steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Run a one-line script
          run: echo Hello, world! from ${{ matrix.image }} on ${{ matrix.os }}

        - name: docker image on ${{ matrix.os }}
          run: |
            docker run ${{ matrix.image }}
                 


