name: Hello World

on: 
    push:
        branches:
        - main
    workflow_dispatch:
#   schedule:
#     - cron: "*/1 * * * *"


jobs:
    deploy:
     strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, ubuntu-20.04]
            image: [alpine, helloworld]
     runs-on: ${{ matrix.os }} 
     steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Run a one-line script
          run: echo Hello, world! from ${{ matrix.image }} on ${{ matrix.os }}

        - name: docker image on ${{ matrix.os }}
          run: |
            docker run ${{ matrix.image }} echo Hello from inside a container!
                 


